version: "2"
services:
  mysql:
    image: "mysql:8.0.19"
    restart: "always"
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "hostgator123"
      MYSQL_DATABASE: "hostgator"
      MYSQL_USER: "hostgator"
      MYSQL_PASSWORD: "hostgator123"
